# Generated by Django 5.1.2 on 2024-11-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('application_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('total_repayment', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, help_text='Optional comments by admin', null=True)),
                ('payment_complete', models.BooleanField(default=False)),
                ('loan_due_date', models.DateField(blank=True, null=True)),
                ('loan_duration', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Loan Application',
                'verbose_name_plural': 'Loan Applications',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bussiness Loan', 'Bussiness Loan'), ('Personal Loan', 'Personal Loan'), ('Emergency Loan', 'Emergency Loan')], max_length=20, unique=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Interest rate for the loan type', max_digits=5)),
                ('loan_duration', models.PositiveIntegerField(choices=[(7, 'One Week'), (30, 'One Month'), (90, '3 Months')])),
                ('description', models.TextField(blank=True, help_text='Description of the loan type', null=True)),
                ('max_loan_amount', models.DecimalField(decimal_places=2, default=100000, help_text='Maximum loan amount for this loan type', max_digits=12)),
            ],
        ),
    ]
