# Generated by Django 5.1.2 on 2024-11-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
