# Generated by Django 5.1.2 on 2024-11-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantype',
            name='max_loan_amount',
            field=models.DecimalField(decimal_places=2, default=50000, help_text='Maximum loan amount for this loan type', max_digits=12),
        ),
    ]
