# Generated by Django 5.1.2 on 2024-11-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_remove_loanapplication_disbursement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Repaid', 'Repaid'), ('Defaulted', 'Defaulted'), ('Disbursed', 'Disbursed')], default='Pending', max_length=10),
        ),
    ]
