# Generated by Django 5.1.2 on 2024-11-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_loantype_max_loan_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loantype',
            options={'verbose_name': 'Loan Type', 'verbose_name_plural': 'Loan Types'},
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='loan_duration',
            field=models.PositiveIntegerField(choices=[(7, 'One Week'), (30, 'One Month'), (90, '3 Months')], help_text='Duration of the loan'),
        ),
    ]
