# Generated by Django 5.1.2 on 2024-11-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_loanapplication_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='total_repayment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
