# Generated by Django 5.1.2 on 2024-11-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberloan',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in days', null=True),
        ),
    ]
