# Generated by Django 5.1.2 on 2024-11-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_memberloan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberloan',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
