# Generated by Django 5.1.2 on 2024-11-10 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleximembers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BUSINESS', 'Business Loan'), ('PERSONAL', 'Personal Loan'), ('EMERGENCY', 'Emergency Loan')], max_length=20)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Interest rate for the loan type', max_digits=5)),
                ('loan_duration', models.PositiveIntegerField(choices=[(7, '1 Week'), (30, '1 Month'), (90, '3 Months')], help_text='Duration of the loan in days')),
                ('description', models.TextField(blank=True, help_text='Description of the loan type', null=True)),
            ],
            options={
                'verbose_name': 'Loan Product',
                'verbose_name_plural': 'Loan Products',
            },
        ),
        migrations.CreateModel(
            name='FlexiCashLoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Repaid', 'Repaid'), ('Defaulted', 'Defaulted'), ('Disbursed', 'Disbursed'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], default='Pending', max_length=10)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('loan_due_date', models.DateField(blank=True, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_repayment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('loan_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='fleximembers.flexicashmember')),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='loanmanagement.loanproduct')),
            ],
            options={
                'verbose_name': 'FlexiCash Loan Application',
                'verbose_name_plural': 'FlexiCash Loan Applications',
                'ordering': ['-application_date'],
            },
        ),
    ]
