# Generated by Django 5.1.2 on 2024-11-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanagement', '0002_alter_loanproduct_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexicashloanapplication',
            options={'ordering': ['-application_date'], 'verbose_name': 'Manage Loan Application', 'verbose_name_plural': 'Manage Loan Applications'},
        ),
        migrations.RenameField(
            model_name='flexicashloanapplication',
            old_name='interest_amount',
            new_name='loan_yield',
        ),
        migrations.RenameField(
            model_name='flexicashloanapplication',
            old_name='loan_profit',
            new_name='outstanding_balance',
        ),
        migrations.RenameField(
            model_name='flexicashloanapplication',
            old_name='requested_amount',
            new_name='principal_amount',
        ),
        migrations.AddField(
            model_name='flexicashloanapplication',
            name='loan_penalty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
