# Generated by Django 5.1.2 on 2024-11-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanagement', '0003_alter_flexicashloanapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexicashloanapplication',
            name='approval_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='flexicashloanapplication',
            name='loan_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disbursed', 'Disbursed'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], default='Pending', max_length=10),
        ),
    ]
