# Generated by Django 5.1.2 on 2024-11-22 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleximembers', '0001_initial'),
        ('loanapplication', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('Repayment', 'Repayment'), ('Disbursemnt', 'Disbursemnt')], default='Repayment', max_length=15)),
                ('narrative', models.CharField(blank=True, max_length=15, null=True)),
                ('state', models.CharField(default='PENDING', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('repayment_type', models.CharField(choices=[('Full', 'Full'), ('Partial', 'Partial')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loanapplication.memberloanapplication')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fleximembers.flexicashmember')),
            ],
            options={
                'verbose_name': 'Loan Transaction',
                'verbose_name_plural': 'Loan Transactions',
                'ordering': ['-date'],
            },
        ),
    ]
