# Generated by Django 5.1.2 on 2024-11-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date'], 'verbose_name': 'M-PESA Transaction', 'verbose_name_plural': 'M-PESA Transactions'},
        ),
    ]
