# Generated by Django 5.1.2 on 2024-11-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipanampesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanMpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('narrative', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mpesa Payment',
                'verbose_name_plural': 'Mpesa Payments',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='MPesaTransaction',
        ),
    ]
