# Generated by Django 5.1.2 on 2024-11-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipanampesa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='narrative',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
