# Generated by Django 5.1.2 on 2024-11-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipanampesa', '0002_mpesatransaction_invoice_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpesatransaction',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='narrative',
        ),
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='channel_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='external_reference',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='provider',
            field=models.CharField(default='m-pesa', max_length=50),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='phone_number',
            field=models.CharField(default='1', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
