# Generated by Django 5.1.2 on 2024-11-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipanampesa', '0003_rename_date_mpesatransaction_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='checkout_request_id',
        ),
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='external_reference',
        ),
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='provider',
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='narrative',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
