# Generated by Django 5.1.2 on 2024-11-14 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipanampesa', '0006_laonmpesatransaction_delete_mpesatransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanMpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, unique=True)),
                ('narrative', models.CharField(blank=True, max_length=255, unique=True)),
                ('state', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 11, 14, 11, 38, 3, 24483, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.DeleteModel(
            name='LaonMpesaTransaction',
        ),
    ]
