# Generated by Django 5.1.2 on 2024-11-14 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipanampesa', '0007_loanmpesatransaction_delete_laonmpesatransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmpesatransaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 14, 11, 52, 51, 722511, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loanmpesatransaction',
            name='narrative',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
