# Generated by Django 5.1.2 on 2024-11-14 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipanampesa', '0008_alter_loanmpesatransaction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmpesatransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loanmpesatransaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 14, 11, 55, 18, 343628, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loanmpesatransaction',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='loanmpesatransaction',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
