# Generated by Django 5.1.2 on 2024-11-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleximembers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flexicashmember',
            old_name='balance',
            new_name='member_balance',
        ),
    ]
