# Generated by Django 5.1.2 on 2024-11-20 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleximembers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Business Loan', 'Business Loan'), ('Personal Loan', 'Personal Loan'), ('Emergency Loan', 'Emergency Loan')], max_length=20, null=True)),
                ('interest_rate', models.DecimalField(choices=[(10, '10% Interest Rate'), (20, '20 % Interest Rate'), (30, '30 % Interest Rate')], decimal_places=2, help_text='Interest rate for the loan type', max_digits=5)),
                ('loan_duration', models.PositiveIntegerField(choices=[(7, '1 Week'), (30, '1 Month'), (90, '3 Months')], help_text='Duration of the loan in days')),
                ('description', models.TextField(blank=True, help_text='Description of the loan type', null=True)),
            ],
            options={
                'verbose_name': 'Loan Product',
                'verbose_name_plural': 'Loan Products',
            },
        ),
        migrations.CreateModel(
            name='MemberLoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_ref', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disbursed', 'Disbursed'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], default='Pending', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('loan_yield', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_repayment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_complete', models.BooleanField(blank=True, default=False, null=True)),
                ('loan_penalty', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('disbursement_date', models.DateTimeField(blank=True, null=True)),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='loanapplication.loanproduct')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='fleximembers.flexicashmember')),
            ],
            options={
                'verbose_name': 'Loan  Application',
                'verbose_name_plural': 'Loan Applications',
                'ordering': ['-application_date'],
            },
        ),
    ]
