# Generated by Django 5.1.2 on 2024-11-10 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleximembers', '0001_initial'),
        ('loanmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disbursed', 'Disbursed'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('loan_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_repayment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_complete', models.BooleanField(default=False)),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='loanmanagement.loanproduct')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='fleximembers.flexicashmember')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('Disbursement', 'Disbursement'), ('Repayment', 'Repayment'), ('Withdrawal', 'Withdrawal')], max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loanapplication.memberloanapplication')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fleximembers.flexicashmember')),
            ],
        ),
        migrations.CreateModel(
            name='LoanStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='fleximembers.flexicashmember')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_entries', to='loanapplication.transaction')),
            ],
            options={
                'verbose_name': 'Statement Entry',
                'verbose_name_plural': 'Statement Entries',
                'ordering': ['-date'],
            },
        ),
    ]
