# Generated by Django 5.1.2 on 2024-11-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberloanapplication',
            name='loan_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Closed', 'Closed')], default='Pending', max_length=20),
        ),
    ]
