# Generated by Django 5.1.2 on 2024-11-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
