# Generated by Django 5.1.2 on 2024-11-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapplication', '0002_alter_loanproduct_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='interest_rate',
            field=models.DecimalField(choices=[(10, '10% Rate'), (20, '20 % Rate'), (30, '30 % Rate')], decimal_places=2, help_text='Interest rate for the loan type', max_digits=5),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='name',
            field=models.CharField(choices=[('Business Loan', 'Business Loan'), ('Personal Loan', 'Personal Loan'), ('Emergency Loan', 'Emergency Loan')], max_length=20, null=True),
        ),
    ]
