# Generated by Django 5.1.2 on 2024-11-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapplication', '0003_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='narrative',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
