# Generated by Django 5.1.2 on 2024-11-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapplication', '0003_alter_loanproduct_interest_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='interest_rate',
            field=models.DecimalField(choices=[(10, '10% Interest Rate'), (20, '20 % Interest Rate'), (30, '30 % Interest Rate')], decimal_places=2, help_text='Interest rate for the loan type', max_digits=5),
        ),
        migrations.AlterField(
            model_name='memberloanapplication',
            name='disbursement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
