# Generated by Django 5.1.2 on 2024-11-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapplication', '0005_transaction_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanstatement',
            options={'ordering': ['-date'], 'verbose_name': 'Mini Statement', 'verbose_name_plural': 'MIni Statements'},
        ),
        migrations.AlterModelOptions(
            name='memberloanapplication',
            options={'ordering': ['-applied_on'], 'verbose_name': 'MemberLoan Loan Application', 'verbose_name_plural': 'Member Loan Applications'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date'], 'verbose_name': 'Loan Transaction', 'verbose_name_plural': 'Loan Transactions'},
        ),
        migrations.RenameField(
            model_name='memberloanapplication',
            old_name='interest_amount',
            new_name='loan_yield',
        ),
        migrations.RenameField(
            model_name='memberloanapplication',
            old_name='loan_balance',
            new_name='outstanding_balance',
        ),
        migrations.RenameField(
            model_name='memberloanapplication',
            old_name='requested_amount',
            new_name='principal_amount',
        ),
        migrations.AddField(
            model_name='memberloanapplication',
            name='loan_penalty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='repayment_type',
            field=models.CharField(choices=[('Full Payment', 'Full'), ('Partial', 'Partial Payment')], default='1', max_length=20),
            preserve_default=False,
        ),
    ]
