# Generated by Django 5.1.2 on 2024-11-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapplication', '0006_alter_loanstatement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='member',
        ),
        migrations.DeleteModel(
            name='LoanStatement',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
